# ===============================================
# CONFIGURAÇÃO GERAL
# ===============================================

# Permite que qualquer cliente se conecte sem autenticação.
# **ATENÇÃO:** Mantenha 'false' em ambiente de produção.
allow_anonymous true


# ===============================================
# LISTENER 1: MQTT Padrão (TCP)
# ===============================================

# Escuta na porta padrão para o protocolo MQTT (TCP)
listener 1883
# Define para escutar em todos os endereços IP da máquina
#bind_address 0.0.0.0


# ===============================================
# LISTENER 2: MQTT sobre WebSockets
# ===============================================

# Escuta na porta 9001, o padrão para WebSockets
listener 9001
# Especifica que o protocolo neste listener é WebSockets
protocol websockets
# Define para escutar em todos os endereços IP da máquina

